### ISSUE TITLE
Allow arbitrary pathing

### ISSUE THREAD

**Issue by TimJones** [Azure/kashti#147]
I am setting up brigade to be accessible via Ingress but I can only have a single public host.
Currently, my Ingress is configured as:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: brigade
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-brigade.example.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: brigade-api
          servicePort: 7744
      - path: /ui
        backend:
          serviceName: brigade-kashti
          servicePort: 80
      - path: /gateway/github
        backend:
          serviceName: brigade-github-gw
          servicePort: 7744
```
The `/api` and `/gateway/github` endpoints work fine, but the `/ui` fails to load Kashti.

Looking into the container, I see that `index.html` has a `<base href="/">` element. Changing this by hand allows the app & assets to load correctly.

A way of setting the 'base' for the application would be very beneficial.

**Comment by andrewrynhard** [comment]
If you set
```
ingress:
  enabled: true
  ...
  paths:
  - /gateway
  ...
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
```
on the brigade gateway ingress, and
```
ingress:
  enabled: true
  ...
  paths:
  - /v1
  ...
  annotations:
    kubernetes.io/ingress.class: nginx
```
on the API ingress object, then you can deploy Kashti as is and things _should_ work (works for me).
